os: linux
dist: bionic

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y python3.7 python3-distutils
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3.7 get-pip.py
  - bash apt_deps.sh
  - bazel build //deeplearning/clgen

before_script:
  - python3 --version
  - python --version
  - bazel --version
  - gcc --version
  - python -m pip list tensorflow | grep tensorflow

script:
  - bazel-bin/deeplearning/clgen/clgen --min_samples 5 --config deeplearning/clgen/tests/data/tiny/config.pbtxt
