os: linux
dist: bionic

language:
  - python

python:
  - "3.7"

services:
  - mysql

install:
  - bash apt_deps.sh
  - sudo ln -s apt_pkg.cpython-{36m,37m}-x86_64-linux-gnu.so
  - bazel build //deeplearning/clgen

before_script:
  - python3 --version
  - python --version
  - bazel --version
  - gcc --version
  - python -m pip list tensorflow | grep tensorflow

script:
  - bazel-bin/deeplearning/clgen/clgen --min_samples 5 --config deeplearning/clgen/tests/data/tiny/config.pbtxt
