os: linux
dist: bionic

language:
  - python

python:
  - "3.7"

services:
  - mysql

install:
  - sudo ln -s apt_pkg.cpython-36m-x86_64-linux-gnu.so apt_pkg.cpython-37m-x86_64-linux-gnu.so
  - sudo ln -s apt_inst.cpython-36m-x86_64-linux-gnu.so apt_inst.cpython-37m-x86_64-linux-gnu.so
  - bash apt_deps.sh
  - sudo cp /usr/lib/python3/dist-packages/ /usr/lib/python3/dist-packages
  - bazel build //deeplearning/clgen

before_script:
  - python3 --version
  - python --version
  - bazel --version
  - gcc --version
  - python -m pip list tensorflow | grep tensorflow

script:
  - bazel-bin/deeplearning/clgen/clgen --min_samples 5 --config deeplearning/clgen/tests/data/tiny/config.pbtxt
