version: 2.1

jobs:
  build_clgen:
    parameters:
      python_version:
        type: string
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Matrix python version
          command: echo <<parameters.python_version>>
      - run:
          name: Bootstrap application
          command: |
            echo -e "cmake\ny\n<<parameters.python_version>>" | bash requirements.apt
      - run:
          command: mkdir build && cd build
      - run:
          name: Build application
          command: ../cmake/bin/cmake .. -DPYTHON=<<parameters.python_version>>
      - run:
          name: Compile application
          command: make -j $(nproc)

workflows:
  version: 2
  python_versions:
    jobs:
      - build_clgen:
          matrix:
            parameters:
              python_version: ["python3.5", "python3.6", "python3.7", "python3.8"]
          name: << matrix.python_version >>
