version: 2.1

jobs:
  build_benchpress:
    parameters:
      python_version:
        type: string
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - when:
          condition: 
            equal: ["from_source", <<parameters.python_version>>]
          steps:
            - run:
                name: Remove global cmake
                command: sudo apt remove cmake
            - run:
                name: Simulate pre-existing necessary packages
                command : |
                  sudo apt update
                  sudo apt install mysql-server libmysqlclient-dev libsqlite3-dev libmysqlclient21 mysql-server-8.0
            - run:
                name: Bootstrap application without sudo
                command: |
                  echo -e "cmake\nn\ny" | bash requirements.apt
      - when:
          condition: 
            not:
              equal: ["from_source", <<parameters.python_version>>]
          steps:
          - run:
              name: Remove global cmake
              command: sudo apt remove cmake
          - run:
              name: Bootstrap application with sudo
              command: |
                echo -e "cmake\ny\n<<parameters.python_version>>\ny" | bash requirements.apt
      - run:
          name: Build application
          command: |
            mkdir build
            cd build
            ../cmake/bin/cmake .. -DPYTHON=<<parameters.python_version>>
      - run:
          name: Compile application
          command: |
            cd build
            make -j $(nproc)

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 6 1,4,7,10,13,16,19,21,24,28 * *"
          filters:
            branches:
              only:
                - master
    # python_versions:
    jobs:
      - build_benchpress:
          matrix:
            parameters:
              python_version: ["python3.6", "python3.7", "python3.8", "from_source"]
          name: << matrix.python_version >>
