version: 2.1

workflows:
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              python: ["python3.5", "python3.6", "python3.7"]
          filters:
            branches:
              only: master

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
        name: "Test"
        command: <<parameters.python>> --version