version: 2.1

jobs:
  build_clgen:
    parameters:
      python_version:
        type: string
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - when:
          condition: 
            equal: ["from_source", <<parameters.python_version>>]
          steps:
            - run:
                name: Bootstrap application without sudo
                command: |
                  echo -e "cmake\nny" | bash requirements.apt
      - when:
          condition: not ["from_source", <<parameters.python_version>>]
          steps:
          - run:
              name: Bootstrap application with sudo
              command: |
                echo -e "cmake\ny\n<<parameters.python_version>>y" | bash requirements.apt
      - run:
          command: mkdir build && cd build
      - run:
          name: Build application
          command: ../cmake/bin/cmake .. -DPYTHON=<<parameters.python_version>>
      - run:
          name: Compile application
          command: make -j $(nproc)

workflows:
  version: 2
  python_versions:
    jobs:
      - build_clgen:
          matrix:
            parameters:
              python_version: ["python3.5", "python3.6", "python3.7", "python3.8", "from_source"]
          name: << matrix.python_version >>
