github_miner {
  path: "test"
  data_format: sql
  big_query {
    credentials: "/home/fivosts/PhD/Code/benchpress/deeplearning/benchpress/github/4th_acc_creds.json"
    language: "opencl"
    export_corpus {
      data_format: sql
      access_token: "2bfd07104166ae9e610db3537f9b680809643305"
      inline_headers: true
    }
  }
}
