github_miner {
  path: "universe_repos"
  data_format: sql
  big_query {
    credentials: "/home/fivosts/PhD/Code/clgen/deeplearning/benchpress/github/4th_acc_creds.json"
    language: "generic"
  }
}
