github_miner {
  path: "/home/foivos/opencl_corpus"
  data_format: folder
  recursive {
  	access_token: "2bfd07104166ae9e610db3537f9b680809643305"
  	flush_limit_K: 52428800
  	corpus_size_K: -1 # That means unlimited
  }
}
